### ISSUE TITLE
can you formally prove the correctness of this greedy algorithm?

### ISSUE THREAD

**Issue by AndrewLisuxin** [kamyu104/LeetCode#123]
https://github.com/kamyu104/LeetCode/blob/1e0b63039edff116a313e8023bc3067f7cc20a78/C%2B%2B/create-maximum-number.cpp#L34
Why does this maxNumber() function give us the maximal result of size k. I try to prove it correctly but fail. Thanks.

**Comment by kamyu104** [comment]
* To have a max number with k digits, the order of digits must be in descending form as possible.
* So the intuitive idea is to have a non-ascending stack to keep max digits like the problem `max binary tree`.
* But with k-digit limitation, we have to limit the number of drops in the stack.
* The trick is here: it could be dropped in greedy manner due to the characteristics of non-ascending stack. The greedy strategy is always to drop the smaller digit in non-ascending stack which is before and smaller than the current digit until all the drops are all used up.
* At the end, the answer would be the top k digits in the final stack (non-ascending digits with some remaining digits).
